[package]
name = "seal"
version = "0.1.0"
authors = ["William Speirs <bill.speirs@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
clap = "2.33"
rmp-serde = "0.14"
serde = "1.0"
serde_derive = "1.0"
ring = "0.16"
zstd = "0.5"
